services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILD_ENV: prod
        container_name: connected-web-prod
        image: connected-web:prod
        restart: always
        ports:
            - "4200:80"
