services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dev-frontend
        ports:
            - "4200:80"   # browse at http://localhost:4200
