services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILD_ENV: prod
        container_name: prod-frontend
        restart: always
        ports:
            - "4200:80"   # browse at http://localhost:4200
