services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILD_ENV: dev
        container_name: connected-web-dev
        image: connected-web:dev
        restart: unless-stopped
        ports:
            - "4200:80"
