export enum ProjectStatusEnum {
    PENDING = 'PENDING',
    NEEDS_REVISION = 'NEEDS_REVISION',
    REVISED = 'REVISED',
    APPROVED = 'APPROVED',
    PUBLISHED = 'PUBLISHED',
    REJECTED = 'REJECTED',
}
