name: Frontend Dev Deployment
on:
    push:
        branches:
            - dev

jobs:
    build-and-deploy:
        name: Deploy Frontend to Dev Server
        runs-on: [ self-hosted, dev, connected, frontend ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Stop and remove old frontend container
                run: |
                    docker compose -f compose.dev.yml down frontend || true

            -   name: Start new frontend container
                run: |
                    docker compose -f compose.dev.yml up -d --build frontend
