name: Frontend Prod Deployment
on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        name: Deploy Frontend to Prod Server
        runs-on: [ self-hosted, prod, connected, frontend ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Stop and remove old frontend container
                run: |
                    docker compose -f compose.prod.yml down frontend || true

            -   name: Start new frontend container
                run: |
                    docker compose -f compose.prod.yml up -d --build frontend
